### ISSUE TITLE
无法运行项目

### ISSUE THREAD

**Issue by huajideshutiao** [NekoAria/YetAnotherPicSearch4Telegram#48]
如题，将项目下载解压后执行python -m userbot无响应，对着代码弄了下配置文件之后又报错：

Traceback (most recent call last):
  File "D:\下载\YetAnotherPicSearch4Telegram-main\__main__.py", line 10, in <module>
    bot.start(bot_token=config.token)
  File "C:\Users\gv922\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\gv922\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
  File "C:\Users\gv922\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\auth.py", line 177, in _start
    await self.sign_in(bot_token=bot_token)
  File "C:\Users\gv922\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\auth.py", line 357, in sign_in
    result = await self(request)
  File "C:\Users\gv922\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\gv922\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\client\users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.AccessTokenInvalidError: The provided token is not valid (caused by ImportBotAuthorizationRequest)

顺便求一下docker版本

**Comment by NekoAria** [comment]
首先，在 `start.sh` 文件所在的同级目录下，创建一个名为 `.env` 的文件。然后，根据 [config.py](https://github.com/NekoAria/YetAnotherPicSearch4Telegram/blob/main/userbot/config.py) 文件中的说明配置必要的选项。其中，必须配置的项目包括：

```
TOKEN=
OWNER_ID=
ALLOWED_CHATS=[]
```

其中，`TOKEN` 是你从 [@BotFather](https://t.me/BotFather) 获取的 bot token。
`OWNER_ID` 是你的 Telegram ID（一个整数值），可以通过 [@userinfobot](https://t.me/userinfobot) 或使用第三方 Telegram 客户端来获取。
`ALLOWED_CHATS` 应为一个数组，包括所有被允许使用该 bot 的群组或频道的 ID（均应为整数格式）。这些 ID 的获取方法多种多样，包括使用各类 bot 或第三方 Telegram 客户端等，具体操作请自行查找相关资料。
关于 docker 版本将在后续补充，目前暂时搁置。
